services:
  - type: web
    name: pujcovna-backend
    runtime: node
    plan: free
    buildCommand: npm install --prefix backend && npm install --prefix frontend --include=dev && npm run build --prefix frontend
    startCommand: npm run migrate --prefix backend && npm start --prefix backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: pujcovna-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false

databases:
  - name: pujcovna-db
    plan: free
    databaseName: pujcovna
    user: pujcovna
